### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Daniel-Mietchen** [coecms/zenmeta#1]
to clarify reusability

**Comment by paolap** [comment]
I will do, currently is really not re-usable, I just need to share it with a couple of collaborators, the branch I'm working on 'reorganise' has apache2.0 embedded in the files

**Comment by paolap** [comment]
Solved in latest commit https://github.com/coecms/zenmeta/commit/f6ed36dedd2b34dd1b8e81f754478edc80a1f24c
